/**
 * PreToolUse hook (matcher: Edit|Write|MultiEdit).
 *
 * Blocks edits to generated / immutable files:
 *  - apps/console/src/routeTree.gen.ts — generated by `tsr generate` (CLAUDE.md:
 *    "never edit it").
 *  - packages/db/prisma/migrations/** — applied migrations are immutable; change
 *    the schema and create a new migration instead.
 *
 * Wired in .claude/settings.json. Reads the hook payload as JSON on stdin and
 * returns a deny decision when the target is protected.
 */
import { readFileSync } from "node:fs";

const PROTECTED: { test: (p: string) => boolean; reason: string }[] = [
  {
    test: (p) => p.endsWith("routeTree.gen.ts"),
    reason:
      "routeTree.gen.ts is generated by TanStack Router (`tsr generate`, runs in build/typecheck). Edit a route file under apps/console/src/routes/ instead; the tree regenerates.",
  },
  {
    test: (p) => /packages\/db\/prisma\/migrations\//.test(p),
    reason:
      "Prisma migrations are immutable once created. Edit packages/db/prisma/schema.prisma and run `bunx prisma migrate dev --name <change>` to create a new migration.",
  },
];

function main(): void {
  const raw = readFileSync(0, "utf8");
  if (!raw.trim()) return;

  let payload: { tool_input?: { file_path?: string } };
  try {
    payload = JSON.parse(raw);
  } catch {
    return;
  }

  const filePath = payload.tool_input?.file_path ?? "";
  const hit = PROTECTED.find((r) => r.test(filePath));
  if (!hit) return;

  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: hit.reason,
      },
    }),
  );
}

main();
