{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memoturn.fullname" . }}-minio
  labels: {{- include "memoturn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memoturn
      app.kubernetes.io/component: minio
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memoturn
        app.kubernetes.io/component: minio
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          args: ["server", "/data"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "memoturn.minioSecretName" . }}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "memoturn.minioSecretName" . }}
                  key: rootPassword
          ports:
            - containerPort: 9000
              name: s3
          resources: {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "mkdir -p /data/{{ .Values.objectStorage.s3.bucket }}"
      volumes:
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.minio.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memoturn.fullname" . }}-minio
  labels: {{- include "memoturn.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: memoturn
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 9000
      targetPort: s3
      name: s3
{{- end }}
