-- AlterTable
ALTER TABLE "Dashboard" ADD COLUMN     "filters" JSONB NOT NULL DEFAULT '[]';

-- AlterTable
ALTER TABLE "Widget" ADD COLUMN     "chartType" TEXT,
ADD COLUMN     "gridH" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "gridW" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "gridX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gridY" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "query" JSONB;
